AuthenticationAndAuthorization/Controllers/AuthenticateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AuthenticationAndAuthorization.Data;
using AuthenticationAndAuthorization.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AuthenticationAndAuthorization.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly AppDbContext _appDbContext;

        public AuthenticateController(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            AppDbContext appDbContext
        )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _appDbContext = appDbContext;
        }

        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
                return RedirectToAction("Login");
            };

            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Login(string userName, string password)
        {
            //login functionality
            var user = await _userManager.FindByNameAsync(userName);


            if (user != null)
            {
                var role = user.Role;

                //sign in
                var signInResult = await _signInManager.PasswordSignInAsync(user.UserName, password, false, false);

                if (signInResult.Succeeded)
                {
                    if (role == "Admin")
                    {
                        return RedirectToAction("Index", "Admin", new { area = "" });
                    }
                    else if (role == "Student")
                    {
                        return RedirectToAction("Index", "Student", new { area = "" });
                    }

                }
            }

            return View();
        }


        [Authorize(Roles = "Admin")]
        public IActionResult AddStudent()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddStudent(string password, string userName, string firstName, string lastName, string homeAddress)
        {
            //register functionality




            var user = new AppUser
            {
                FirstName = firstName,
                LastName = lastName,
                HomeAddress = homeAddress,
                UserName = userName,
                Role = "Student"
            };

            var _password = password;

            var result = await _userManager.CreateAsync(user, _password);

            if (result.Succeeded)
            {
                user = await _userManager.FindByNameAsync(user.UserName);

                var prelim = InitializeGrades("Prelim");
                var midterm = InitializeGrades("Midterm");
                var preFinal = InitializeGrades("Prefinal");
                var final = InitializeGrades("Final");
                await _appDbContext.AddRangeAsync(prelim, midterm, preFinal, final);
                await _appDbContext.SaveChangesAsync();

                var grade = new StudentGrades
                {
                    AppUserID = user.Id,
                    PrelimID = prelim.ID,
                    MidtermID = midterm.ID,
                    PrefinalID = preFinal.ID,
                    FinalID = final.ID
                };

                await _appDbContext.AddAsync(grade);
                await _appDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Admin", new { area = "" });
        }

        public GradesPerTerm InitializeGrades(string term)
        {
            var gpt = new GradesPerTerm
            {
                Term = term,
                Grade = 0
            };
            string[] types = { "Quiz1", "Quiz2", "Quiz3", "Assignment1", "Assignment2", "Assignment3" };

            var item = new ItemScore();
            for (int i = 0; i < types.Length; i++)
            {
                item = new ItemScore
                {
                    TotalItems = 0,
                    Score = 0,
                    Grade = 0,
                    Type = types[i]
                };

                _appDbContext.Add(item);
                _appDbContext.SaveChanges();

                switch (i)
                {
                    case 0:
                        gpt.Quiz1ID = item.ID;
                        break;
                    case 1:
                        gpt.Quiz2ID = item.ID;
                        break;
                    case 2:
                        gpt.Quiz3ID = item.ID;
                        break;
                    case 3:
                        gpt.Assignment1ID = item.ID;
                        break;
                    case 4:
                        gpt.Assignment2ID = item.ID;
                        break;
                    case 5:
                        gpt.Assignment3ID = item.ID;
                        break;
                    default:
                        break;
                }

            }

            return gpt;
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

    }
    
}

AuthenticationAndAuthorization/Views/Admin/AddGrade.cshtml
@model AuthenticationAndAuthorization.Models.ItemScore

<h1 class="page-title">Add Grade</h1>

<form asp-action="AddGrade" method="post">
    <input type="hidden" asp-for="ID"/>
    <input type="hidden" asp-for="Type"/>
    <label asp-for="TotalItems"></label>
    <input asp-for="TotalItems" id="totalItems" type="number" name="totalItems" value="" />
    <label asp-for="Score"></label>
    <input asp-for="Score" id="score" type="number" name="score" value="" /> 
    <button type="submit">Submit</button>
</form>

AuthenticationAndAuthorization/Views/Admin/Delete.cshtml
@model AuthenticationAndAuthorization.Models.AppUser


    <h3>Confirm Delete?</h3>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="button-submit"/>
        <a asp-action="Index" class="back-to-list">Back to List</a>
    </form>

AuthenticationAndAuthorization/Views/Admin/Details.cshtml
@model AuthenticationAndAuthorization.Models.AppUser


<h1 class="page-title">Details</h1>
<div class="student-details">
    <div class="student-details--container">
        <p class="student-details--label">Name:</p>
        <p class="student-details--info">@Model.FirstName , @Model.LastName</p>
    </div>
    <div class="student-details--container">
        <p class="student-details--label">Address:</p>
        <p class="student-details--info">@Model.HomeAddress</p>
    </div>
</div>

AuthenticationAndAuthorization/Views/Admin/Edit.cshtml
@model AuthenticationAndAuthorization.Models.AppUser

    <h1 class="page-title">Edit</h1>

    <form asp-action="Edit" method="post">
        <input type="hidden" name="userName" value="" asp-for="UserName"/>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" type="text" name="firstName" value="" />
        <label asp-for="LastName"></label>
        <input asp-for="LastName" type="text" name="lastName" value="" />
        <label asp-for="HomeAddress">Address</label>

        <textarea asp-for="HomeAddress"></textarea>
        
        <button type="submit" value="Save">Save</button>
    </form>
    

AuthenticationAndAuthorization/Views/Admin/Grades.cshtml
@model AuthenticationAndAuthorization.Models.StudentGrades
<h1 class="page-title">Grades Page</h1>

<table>
    <thead>
        <tr>
            <th>Term</th>
            <th>Quiz1</th>
            <th>Quiz2</th>
            <th>Quiz3</th>
            <th>Assignment1</th>
            <th>Assignment2</th>
            <th>Assignment3</th>
            <th>Grades</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Prelim</td>
            <td>@Model.Prelim.Quiz1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Quiz1.ID">Edit</a></td>
            <td>@Model.Prelim.Quiz2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Quiz2.ID">Edit</a></td>
            <td>@Model.Prelim.Quiz3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Quiz3.ID">Edit</a></td>
            <td>@Model.Prelim.Assignment1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Assignment1.ID">Edit</a></td>
            <td>@Model.Prelim.Assignment2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Assignment2.ID">Edit</a></td>
            <td>@Model.Prelim.Assignment3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prelim.Assignment3.ID">Edit</a></td>
            <td>@Model.Prelim.Grade</td>
        </tr>
        <tr>
            <td>Midterm</td>
            <td>@Model.Midterm.Quiz1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Quiz1.ID">Edit</a></td>
            <td>@Model.Midterm.Quiz2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Quiz2.ID">Edit</a></td>
            <td>@Model.Midterm.Quiz3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Quiz3.ID">Edit</a></td>
            <td>@Model.Midterm.Assignment1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Assignment1.ID">Edit</a></td>
            <td>@Model.Midterm.Assignment2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Assignment2.ID">Edit</a></td>
            <td>@Model.Midterm.Assignment3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Midterm.Assignment3.ID">Edit</a></td>
            <td>@Model.Midterm.Grade</td>
        </tr>
        <tr>
            <td>Prefinal</td>
            <td>@Model.Prefinal.Quiz1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Quiz1.ID">Edit</a></td>
            <td>@Model.Prefinal.Quiz2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Quiz2.ID">Edit</a></td>
            <td>@Model.Prefinal.Quiz3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Quiz3.ID">Edit</a></td>
            <td>@Model.Prefinal.Assignment1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Assignment1.ID">Edit</a></td>
            <td>@Model.Prefinal.Assignment2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Assignment2.ID">Edit</a></td>
            <td>@Model.Prefinal.Assignment3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Prefinal.Assignment3.ID">Edit</a></td>
            <td>@Model.Prefinal.Grade</td>
        </tr>
        <tr>
            <td>Final</td>
            <td>@Model.Final.Quiz1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Quiz1.ID">Edit</a></td>
            <td>@Model.Final.Quiz2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Quiz2.ID">Edit</a></td>
            <td>@Model.Final.Quiz3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Quiz3.ID">Edit</a></td>
            <td>@Model.Final.Assignment1.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Assignment1.ID">Edit</a></td>
            <td>@Model.Final.Assignment2.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Assignment2.ID">Edit</a></td>
            <td>@Model.Final.Assignment3.Grade <a asp-action="AddGrade" asp-route-id="@Model.Final.Assignment3.ID">Edit</a></td>
            <td>@Model.Final.Grade</td>
        </tr>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <th>Prelim Grade</th>
            <th>Midterm Grade</th>
            <th>Prefinal Grade</th>
            <th>Final Grade</th>
            <th>Subject Grade</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Prelim.Grade</td>
            <td>@Model.Midterm.Grade</td>
            <td>@Model.Prefinal.Grade</td>
            <td>@Model.Final.Grade</td>
            <td>@Model.SubjectGrade</td>
        </tr>
    </tbody>
</table>

AuthenticationAndAuthorization/Views/Admin/Index.cshtml
<div class="showcase">
    <div class="showcase--cta">
        <h1 class="showcase--cta--intro">Welcome <br/> Admin!</h1>
        <hr/>
        

        <a class="showcase--cta--btn btn-secondary--rectangle" asp-controller="Authenticate" asp-action="AddStudent">Sign Your Student Up! </a>
       
    </div>
    <div class="showcase--svg">
        <img src="~/My Sass Library/img/AdminHomePage.png" />
    </div>
</div>

AuthenticationAndAuthorization/Views/Admin/StudentList.cshtml
@model IEnumerable<
        AuthenticationAndAuthorization.Models.AppUser>

<div class="table-area">
    <table class="table-area-content">
        <thead>
            <tr>
                <th>
                    Students
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.Role == "Student")
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                            <a asp-action="Grades" asp-route-id="@item.Id">Grades</a> 
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>